[tools]
delta = "latest"
eza = "latest"
fd = "latest"
ripgrep = "latest"
ruby = "latest"
rust = "latest"
yazi = "latest"
bat = "latest"
fzf = "latest"
zellij = "latest"
zoxide = "latest"
neovim = "latest"
node = "lts"
